import type { KnipConfig } from 'knip'

const config: KnipConfig = {
  expo: {
    entry: ['app/**/*.{ts,tsx}'],
  },

  ignore: [
    // Read tab WIP — intentionally kept, not routed from app/ yet.
    'src/pages/book-reader/**',
    'src/pages/books-list/**',
    // Bible book names data for the Read tab.
    'src/shared/api/db/bibleBookNames.ts',
    // Book/fetched-DB domain for the upcoming Read tab.
    'src/entities/sermon/model/sermon.ts',
    'src/entities/sermon/model/fetched.ts',
    // orval output — regenerated by `yarn api:generate`, never hand-edited.
    'src/shared/api/generated/**',
  ],

  // Dev utilities invoked from package.json scripts, never from JS.
  ignoreBinaries: ['fzf', 'adb'],

  // Referenced only from app.config.ts (config plugins) and scripts/*.mjs, which sit
  // outside the `project` globs below — knip cannot load app.config.ts at all without
  // EXPO_PUBLIC_* env vars, so these would always read as unused.
  ignoreDependencies: [
    'expo-splash-screen', // app.config.ts plugins[] — splash screen config
    'expo-system-ui', // native module presence predates the custom Material You theme
    'sharp', // scripts/{analyze-icon,create-fallback-artwork,create-notification-icon}.mjs
    'xml-js', // FB2 parsing for the Read tab
  ],

  jest: true,

  project: ['app/**/*.{ts,tsx}', 'src/**/*.{ts,js,tsx,jsx}'],

  rules: {
    dependencies: 'warn',
    devDependencies: 'warn',
    optionalPeerDependencies: 'warn',
    unlisted: 'off',
  },
}

export default config
