import type { KnipConfig } from 'knip'

const config: KnipConfig = {
  // Manually invoked asset-generation dev utilities — nothing imports them, and
  // they would otherwise read as unused files (which in turn masks `sharp` usage).
  entry: [
    'scripts/analyze-icon.mjs',
    'scripts/create-fallback-artwork.mjs',
    'scripts/create-notification-icon.mjs',
    // Read tab WIP — kept as an entry, not an ignore: its imports keep the
    // shared/ui list-item surface (ListItemSize, TouchableListItem,
    // OnPressTouchableListItem) alive instead of reading as unused.
    'src/pages/books-list/**/*.{ts,tsx}',
  ],

  expo: {
    // `config: []` keeps the expo plugin from evaluating app.config.ts. That file
    // both validates EXPO_PUBLIC_* env (knip never loads .env, unlike the Expo
    // CLI) and registers local config plugins as function references — knip's
    // getPackageNameFromModuleSpecifier calls charCodeAt on those and crashes.
    // app/ entries are declared explicitly below, so skipping the file loses nothing.
    config: [],
    entry: ['app/**/*.{ts,tsx}'],
  },

  ignore: [
    // Read tab WIP — intentionally kept, not routed from app/ yet.
    'src/pages/book-reader/**',
    // Bible book names data for the Read tab.
    'src/shared/api/db/bibleBookNames.ts',
    // Book/fetched-DB domain for the upcoming Read tab.
    'src/entities/sermon/model/sermon.ts',
    'src/entities/sermon/model/fetched.ts',
    // PlaylistData here is consumed only by the knip-ignored reader-domain
    // fetched types (Read tab WIP); the barrel's PlaylistData stays live.
    'src/entities/playlist/@x/sermon.ts',
    // orval output — regenerated by `yarn api:generate`, never hand-edited.
    'src/shared/api/generated/**',
  ],

  // Dev utilities invoked from package.json scripts, never from JS.
  ignoreBinaries: ['fzf', 'adb'],

  // Referenced only from config files that live outside the `project` globs below —
  // knip cannot load app.config.ts at all without EXPO_PUBLIC_* env vars, so these
  // would always read as unused.
  ignoreDependencies: [
    '@feature-sliced/steiger-plugin', // steiger.config.ts — FSD rule set
    'expo-splash-screen', // app.config.ts plugins[] — splash screen config
    'ts-node', // jest loads jest.config.ts (TypeScript) through ts-node at runtime — implicit, not imported
    'xml-js', // FB2 parsing for the Read tab
  ],

  jest: true,

  project: ['app/**/*.{ts,tsx}', 'scripts/**/*.{js,mjs}', 'src/**/*.{ts,js,tsx,jsx}'],

  rules: {
    dependencies: 'warn',
    devDependencies: 'warn',
    optionalPeerDependencies: 'warn',
    unlisted: 'off',
  },
}

export default config
