import { StyleSheet } from 'react-native'
import { COLORS, FONT_SIZES, INDENTS, MIN_TOUCH_TARGET, RADIUSES } from 'shared/ui/theme'

export const styles = StyleSheet.create({
  banner: { borderRadius: RADIUSES.low, marginTop: INDENTS.medium, padding: INDENTS.medium },
  bannerText: { fontSize: FONT_SIZES.sm },
  centered: { alignItems: 'center', flex: 1, justifyContent: 'center' },
  container: { flex: 1 },
  controls: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: INDENTS.low,
    marginBottom: INDENTS.medium,
  },
  error: { fontSize: FONT_SIZES.sm, marginBottom: INDENTS.medium },
  failedList: { marginTop: INDENTS.low },
  failedRow: { fontSize: FONT_SIZES.sm, marginTop: INDENTS.lowest },
  grid: { gap: INDENTS.low },
  gridImage: { aspectRatio: 1, borderRadius: RADIUSES.low, width: '100%' },
  header: { paddingBottom: INDENTS.medium },
  headerRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: INDENTS.medium,
    marginBottom: INDENTS.medium,
  },
  headerText: { flex: 1 },
  listContent: { padding: INDENTS.medium },
  orphanBadge: {
    borderRadius: RADIUSES.low,
    paddingHorizontal: INDENTS.low,
    paddingVertical: INDENTS.lowest,
  },
  orphanBadgeText: { fontSize: FONT_SIZES.sm, fontWeight: '600' },
  orphanInfo: { flex: 1 },
  orphanMeta: { fontSize: FONT_SIZES.sm, marginTop: 2 },
  orphanName: { fontSize: FONT_SIZES.base, fontWeight: '600' },
  orphanNote: { fontSize: FONT_SIZES.sm },
  orphanRow: {
    alignItems: 'center',
    borderRadius: RADIUSES.low,
    flexDirection: 'row',
    gap: INDENTS.medium,
    marginTop: INDENTS.low,
    padding: INDENTS.low,
  },
  primaryButton: {
    alignItems: 'center',
    borderRadius: RADIUSES.low,
    justifyContent: 'center',
    minHeight: MIN_TOUCH_TARGET,
    paddingHorizontal: INDENTS.medium,
  },
  primaryButtonText: { color: COLORS.white, fontSize: FONT_SIZES.base, fontWeight: '600' },
  progressFill: { backgroundColor: COLORS.primary, height: '100%' },
  progressTrack: {
    borderRadius: RADIUSES.low,
    height: 6,
    marginTop: INDENTS.low,
    overflow: 'hidden',
  },
  secondaryButton: {
    alignItems: 'center',
    borderColor: COLORS.disabled,
    borderRadius: RADIUSES.low,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: MIN_TOUCH_TARGET,
    paddingHorizontal: INDENTS.medium,
  },
  sectionTitle: { fontSize: FONT_SIZES.lg, fontWeight: '700', marginTop: INDENTS.high },
  tile: { borderRadius: RADIUSES.middle, borderWidth: 1, overflow: 'hidden' },
  tileBadge: {
    backgroundColor: COLORS.primary,
    borderRadius: RADIUSES.low,
    left: INDENTS.low,
    paddingHorizontal: INDENTS.low,
    paddingVertical: INDENTS.lowest,
    position: 'absolute',
    top: INDENTS.low,
  },
  tileBadgeText: { color: COLORS.white, fontSize: FONT_SIZES.xs, fontWeight: '700' },
  tileBody: { padding: INDENTS.low },
  tileDelete: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.55)',
    borderRadius: RADIUSES.round,
    height: 28,
    justifyContent: 'center',
    position: 'absolute',
    right: INDENTS.low,
    top: INDENTS.low,
    width: 28,
  },
  tileMeta: { fontSize: FONT_SIZES.sm },
  tileName: { fontSize: FONT_SIZES.sm, fontWeight: '600' },
})
