import { Playlist } from '../types';

export const secondCorinthiansPlaylist: Playlist = {
  title: 'Второе послание к коринфянам',
  previewUrl: 'https://slovo-istini.com/image/categories/67/2_korinfyanam.jpg',
  list: [
    {
      title: 'Глава 1',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 2',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 3',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 4',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 5',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 6',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 7',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 8',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 9',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 10',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 11',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 12',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 13',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 14',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 15',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 16',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
  ],
};
