import { Playlist } from '../types';

export const titusPlaylist: Playlist = {
  title: 'Послание к Титу',
  previewUrl:
    'https://slovo-istini.com/image/categories/15/whatsapp_image_2022-11-02_at_21.01.38.jpeg',
  list: [
    {
      title: 'Глава 1',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 2',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 3',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 4',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 5',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 6',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 7',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 8',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 9',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 10',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 11',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 12',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 13',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 14',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 15',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
    {
      title: 'Глава 16',
      list: [
        {
          title: '',
          youtubeUrl: '',
          audioUrl: '',
          textFileUrl: '',
          description: '',
        },
      ],
    },
  ],
};
