export const CURRENT_PLAYBACK_RATE = 'currentPlaybackRate'
export const CURRENT_SOUND_POSITION = 'currentSoundPosition'
export const CURRENT_SOUND_DURATION = 'currentSoundDuration'
export const CURRENT_SOUND_VOLUME = 'currentSoundVolume'
export const CURRENT_AUDIO = 'currentAudio'
export const CURRENT_PLAYLIST = 'currentPlaylist'
export const CURRENT_REPEAT_MODE = 'currentRepeatMode'
export const PLAYER_STARTUP_ATTEMPTS = 'playerStartupAttempts'
